config/routes.rb
Rails.application.routes.draw do
 
  get 'categories/index'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/create'
  get 'category/index'
  get 'category/edit'
  get 'category/destroy'
  get 'category/new'
  get 'category/create'
  get 'categories/listofSubCategories'
  
  resources :designations
  
  get 'vip_ref_transfers/index'
  get 'vip_ref_transfers/new'
  get 'vip_ref_transfers/delete'
  get 'vip_ref_summaries/new'
  get 'vip_ref_summaries/index'
  get 'vip_ref_summaries/create'
  get 'vip_ref_summaries/destroy'
  get 'vip_ref_summaries/edit'
  get 'vip_ref_summaries/update'

  get 'vip_ref_app/inbox_section'
  get 'vip_ref_app/inbox'
  get 'vip_ref_app/draft'
  get 'vip_ref_app/sent'
  get 'vip_ref_app/home'
  get 'vip_ref_app/homescreen'
  get 'vip_ref_app/pending_report'
  get 'vip_ref_app/pending_report_1'
  get 'vip_ref_app/disposalreport'

  get 'vip_ref_app/monthwisereport'
  get 'vip_ref_app/statewisereport'
  
  
  
  get 'vip_ref_app/category_wise_pendency'
  get 'vip_ref_app/report'

  
  get 'vip_ref_app/closed'
  get 'vip_ref_app/chart'

  get 'vip_reference_movements/index'

  get 'vip_references/report'
  get 'vip_references/index'

  get 'vip_references/update'

  get 'vip_references/delete'

  get 'vip_references/new'

  get 'complaint_status/index'

  get 'complaint_status/update'

  get 'complaint_status/delete'

  get 'complaint_status/new'

  get 'complaint_status/create'
  
  root 'vip_ref_app#homescreen'
  resources :categories
  resources :vip_categories do
    member do
      get :referencelist
    end
  end
  resources :vip_ref_statuses
  resources :sections do
      member do
        
        get :pending_lessthan_1mth
        get :pending_lessthan_3mth
        get :pending_morethan_3mth
        get :updated_today
        
      end
  end
  
  resources :statuses
  resources :designations
  resources :countries do
    get 'update_states'
    resources :states
  end
  match '/complaints/search_form' => 'complaints#search_form', :via=> :get, :as => :search_form

  resources :complaints do
    resources :complaint_movements
    collection do
      get 'home'
      get 'move'
     end
  end
  
  resources :complaint_types
  resources :handlers
  resources :offices do
      resources :contacts do
        resources :feedbacks do
          resources :feedback_replies
        end
        
      end 
  end
    resources :vip_references do
    resources :vip_ref_summaries
    member do
      get :send
      post :move_to_inbox
    end

    resources :vip_ref_transfers do
    end
    
    resources :vip_ref_movements do
      get 'read'
      collection do
        get 'send'
      end
    end
  end
  
  resources :homes

  devise_for :users, :controllers => {:registrations => "registrations",:sessions=>"sessions"},path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}

end

app/models/office.rb
class Office < ActiveRecord::Base
  validates :name,length: { in: 3..20,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
      },presence:true
  validates :room_no,length: { in: 3..6,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
      },presence:true
  validates :incharge_name,length: { in: 3..20,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
      },presence:true
      
  validates :parent_office ,presence:true
  validates :designation, presence: true    
  
  default_scope {order('name ASC')}
  has_many :contacts
    
  belongs_to :incharge, class_name: "Contact"
  
  belongs_to :parent_office , :class_name => 'Office'
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all.paginate(page: params[:page], per_page: Rails.application.config.records_per_page)

  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :room_no, :floor, :incharge_name,:parent_office_id,:designation,:incharge_id)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.haml
= form_for(@office) do |f|
  - if @office.errors.any?
    #error_explanation
      %h4
        = pluralize(@office.errors.count, "error")
        prohibited this office from being saved:
      /
        %ul
          - @office.errors.full_messages.each do |message|
            %li= message
  %div.row.top-buffer
    %div.col-md-4= f.label :name
    %div.col-md-8= f.text_field :name, :class=>'form-control'
  %div.row.top-buffer
    %div.col-md-4= f.label :room_no
    %div.col-md-8= f.text_field :room_no, :class=>'form-control'
  %div.row.top-buffer
    %div.col-md-4= f.label :floor
    %div.col-md-8= f.text_field :floor, :class=>'form-control'
  %div.row.top-buffer
    %div.col-md-4= f.label :incharge_name
    %div.col-md-8= f.text_field :incharge_name, :class=>'form-control'
  %div.row.top-buffer
    %div.col-md-4= f.label :incharge_id
    %div.col-md-8= f.collection_select(:incharge_id, Contact.all, :id,:name,{}, {:class=>'form-control'})  
    
  %div.row.top-buffer
    %div.col-md-4= f.label :designation
    %div.col-md-8= f.text_field :designation, :class=>'form-control'
  %div.row.top-buffer
    %div.col-md-4= f.label :parent_office
    %div.col-md-4= f.collection_select(:parent_office_id, Office.all, :id,:name,{}, {:class=>'form-control'})  

  %div.row.top-buffer
    %div.col-md-12
      = f.submit :class=>'btn btn-default'

app/views/offices/_form1.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :room_no %><br>
    <%= f.text_field :room_no %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :incharge_name %><br>
    <%= f.text_field :incharge_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offices/edit.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="Editing Office"
  %div.panel-body
    %div.col-md-8
      = render 'form'
    %div.col-md-4

= link_to 'Show', @office
|
= link_to 'Back', offices_path

app/views/offices/edit1.html.erb
<h1 class="header">Editing office</h1>
<%= render 'form' %>
<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="List Offices"
  %div.panel-body
    %table.table
      %thead
        %tr
          %th #
          %th Office Name
          %th Incharge name
          %th Designation
          %th Room no
          %th Floor
          %th Quick Action
      %tbody
        %tr
          = will_paginate @offices, renderer: BootstrapPagination::Rails
        - @offices.each_with_index do |office,index|
          %tr
            - if params[:page].to_i == 0
              %td= index+1
            - else
              %td= (params[:page].to_i-1)*10+index+1
            %td=link_to "#{office.name}", office
            -if !office.incharge.nil?
              %td= link_to "#{office.try(:incharge).try(:name)}", office_contact_path(office,office.incharge)
            -else 
              %td= office.try(:incharge).try(:name)
            %td= office.designation
            %td= office.room_no
            %td= office.floor
            %td
              = icon_link_to  edit_office_path(office),{:icon => "glyphicon glyphicon-edit"},{title:'Edit'}
              |
              = icon_link_to office,{:icon => "glyphicon glyphicon-trash"},{:title=>'Delete',:method => :delete, :data => { :confirm => 'Are you sure?' }}
%br
  = link_to 'New Office', new_office_path

app/views/offices/new.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="New Office"
  %div.panel-body
    %div.col-md-8
      = render 'form'
    %div.col-md-4
= link_to 'Back', offices_path

app/views/offices/show.html.haml
%p#notice= notice
%div.panel.panel-info
  %div.panel-heading
    ="Show Office Details"
  %div.panel-body
    %table.table
      %tr
        %td= "Office Name"
        %td=@office.name
      %tr
        %td= "Room No"
        %td= @office.room_no
      %tr
        %td= "Floor"
        %td= @office.floor
      %tr
        %td= "Incharge Name"
        %td= @office.incharge_name

= link_to 'Edit', edit_office_path(@office)
|
= link_to 'Back', offices_path

app/views/offices/show1.html.erb
<h1 class="header">Office Details</h1>
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @office.name %>
</p>
<p>
  <strong>Room no:</strong>
  <%= @office.room_no %>
</p>
<p>
  <strong>Floor:</strong>
  <%= @office.floor %>
</p>
<p>
  <strong>Incharge name:</strong>
  <%= @office.incharge_name %>
</p>
<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>