config/routes.rb
Rails.application.routes.draw do
 
  get 'categories/index'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/create'
  get 'category/index'
  get 'category/edit'
  get 'category/destroy'
  get 'category/new'
  get 'category/create'
  get 'categories/listofSubCategories'
  
  resources :designations
  
  get 'vip_ref_transfers/index'
  get 'vip_ref_transfers/new'
  get 'vip_ref_transfers/delete'
  get 'vip_ref_summaries/new'
  get 'vip_ref_summaries/index'
  get 'vip_ref_summaries/create'
  get 'vip_ref_summaries/destroy'
  get 'vip_ref_summaries/edit'
  get 'vip_ref_summaries/update'

  get 'vip_ref_app/inbox_section'
  get 'vip_ref_app/inbox'
  get 'vip_ref_app/draft'
  get 'vip_ref_app/sent'
  get 'vip_ref_app/home'
  get 'vip_ref_app/homescreen'
  get 'vip_ref_app/pending_report'
  get 'vip_ref_app/pending_report_1'
  get 'vip_ref_app/disposalreport'

  get 'vip_ref_app/monthwisereport'
  get 'vip_ref_app/statewisereport'
  
  
  
  get 'vip_ref_app/category_wise_pendency'
  get 'vip_ref_app/report'

  
  get 'vip_ref_app/closed'
  get 'vip_ref_app/chart'

  get 'vip_reference_movements/index'

  get 'vip_references/report'
  get 'vip_references/index'

  get 'vip_references/update'

  get 'vip_references/delete'

  get 'vip_references/new'

  get 'complaint_status/index'

  get 'complaint_status/update'

  get 'complaint_status/delete'

  get 'complaint_status/new'

  get 'complaint_status/create'
  
  root 'vip_ref_app#homescreen'
  resources :categories
  resources :vip_categories do
    member do
      get :referencelist
    end
  end
  resources :vip_ref_statuses
  resources :sections do
      member do
        
        get :pending_lessthan_1mth
        get :pending_lessthan_3mth
        get :pending_morethan_3mth
        get :updated_today
        
      end
  end
  
  resources :statuses
  resources :designations
  resources :countries do
    get 'update_states'
    resources :states
  end
  match '/complaints/search_form' => 'complaints#search_form', :via=> :get, :as => :search_form

  resources :complaints do
    resources :complaint_movements
    collection do
      get 'home'
      get 'move'
     end
  end
  
  resources :complaint_types
  resources :handlers
  resources :offices do
      resources :contacts do
        resources :feedbacks do
          resources :feedback_replies
        end
        
      end 
  end
    resources :vip_references do
    resources :vip_ref_summaries
    member do
      get :send
      post :move_to_inbox
    end

    resources :vip_ref_transfers do
    end
    
    resources :vip_ref_movements do
      get 'read'
      collection do
        get 'send'
      end
    end
  end
  
  resources :homes

  devise_for :users, :controllers => {:registrations => "registrations",:sessions=>"sessions"},path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}

end

app/models/vip_category.rb
class VipCategory < ActiveRecord::Base
  
  validates :name,length: { in: 3..20,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
      },presence:true
  
  validates :s_name,length: { in: 2..10,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
      },presence:true
      
    validates :category,presence: true
       
  has_many :vip_references
  default_scope { order('name ASC') }
  scope :default, lambda { where(:default => true) }
  
  belongs_to :category
  
  def isVip?
    if self.category.id ==1 
      return true
    else 
      return false
    end
  end
  
  def to_s
    "#{name}"
  end
  
end

app/controllers/vip_categories_controller.rb
class VipCategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_vip_category, only: [:show, :edit, :update, :destroy,:referencelist]

  # GET /vip_categories
  # GET /vip_categories.json
  def index
    @vip_categories = VipCategory.all.paginate(page: params[:page], per_page: 5)
  end
  def referencelist
      @referencelist= @vip_category.vip_references.pending.paginate(page: params[:page], per_page: 10)
  end
  # GET /vip_categories/1
  # GET /vip_categories/1.json
  def show
  end

  # GET /vip_categories/new
  def new
    @vip_category = VipCategory.new
  end

  # GET /vip_categories/1/edit
  def edit
  end

  # POST /vip_categories
  # POST /vip_categories.json
  def create
    @vip_category = VipCategory.new(vip_category_params)

    respond_to do |format|
      if @vip_category.save
        format.html { redirect_to @vip_category, notice: 'Vip category was successfully created.' }
        format.json { render :show, status: :created, location: @vip_category }
      else
        format.html { render :new }
        format.json { render json: @vip_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vip_categories/1
  # PATCH/PUT /vip_categories/1.json
  def update
    respond_to do |format|
      if @vip_category.update(vip_category_params)
        format.html { redirect_to @vip_category, notice: 'Vip category was successfully updated.' }
        format.json { render :show, status: :ok, location: @vip_category }
      else
        format.html { render :edit }
        format.json { render json: @vip_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vip_categories/1
  # DELETE /vip_categories/1.json
  def destroy
    @vip_category.destroy
    respond_to do |format|
      format.html { redirect_to vip_categories_url, notice: 'Vip category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vip_category
      @vip_category = VipCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vip_category_params
      params.require(:vip_category).permit(:name,:default,:s_name,:category_id)
    end
end

app/helpers/vip_categories_helper.rb
module VipCategoriesHelper
end

app/views/vip_categories/_form.html.haml
= form_for @vip_category do |f|
  - if @vip_category.errors.any?
    #error_explanation
      %h4= "#{pluralize(@vip_category.errors.count, "error")} prohibited this vip category from being saved:"
      /
        %ul
          - @vip_category.errors.full_messages.each do |msg|
            %li= msg
  %div.row.top-buffer
    %div.col-md-4= f.label :name
    %div.col-md-8= f.text_field :name, {:class=>'form-control'}
  %div.row.top-buffer
    %div.col-md-4= f.label :s_name
    %div.col-md-8= f.text_field :s_name, {:class=>'form-control'}
  %div.row.top-buffer
    %div.col-md-4=f.label :category
    %div.col-md-4= f.collection_select(:category_id, Category.all, :id,:name,{}, {:class=>'form-control'})

  %div.row.top-buffer
    %div.col-md-4= f.label :default
    %div.col-md-8= f.check_box :default , {:class=>'form-control'}

  %div.row.top-buffer
    %div.col-md-9
    %div.col-md-3
      -if @vip_category.new_record?
        = f.submit 'Create', :class=> 'btn btn-primary'
      -else
        = f.submit 'Update', :class=> 'btn btn-primary'

app/views/vip_categories/edit.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="Edit Category"
  %div.panel-body
    %div.col-md-8
      = render 'form'
    %div.col-md-4

= link_to 'Show', @vip_category

= link_to 'Back', vip_categories_path

app/views/vip_categories/index.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="List VIP Categories"
  %div.panel-body
    %table.table
      %thead
        %tr
          %th= "#"
          %th= "Name"
          %th= "Short Name"
          %th= "Default"
          %th= "Category"
          %th= "Created At"
          %th= "Updated At"
          %th= "Quick Action"
      %tbody      
        %tr
          = will_paginate @vip_categories, renderer: BootstrapPagination::Rails
        - @vip_categories.each_with_index do |vip_category,index|
          %tr
            -if params[:page].to_i == 0
              %td= index+1
            -else
              %td= (params[:page].to_i-1)*5+index+1

            %td=link_to "#{vip_category.name}", vip_category
            %td= vip_category.s_name
            %td= check_box_tag :default ,vip_category.default,vip_category.default, {:class=>'form-control',:disabled=>true}
            %td= vip_category.category.name
            %td= l vip_category.created_at
            %td= l vip_category.updated_at
            /
              %td= link_to 'Show', vip_category
              %td= link_to 'Edit', edit_vip_category_path(vip_category)
              %td= link_to 'Destroy', vip_category, :method => :delete, :data => { :confirm => 'Are you sure?' }
            %td
              = icon_link_to  edit_vip_category_path(vip_category),{:icon => "glyphicon glyphicon-edit"},{title:'Edit'}
              |
              = icon_link_to vip_category,{:icon => "glyphicon glyphicon-trash"},{:title=>'Delete',:method => :delete, :data => { :confirm => 'Are you sure?' }}


%br

= link_to 'New VIP Category', new_vip_category_path

app/views/vip_categories/new.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="New Category"
  %div.panel-body
    %div.col-md-8
      = render 'form'
    %div.col-md-4
= link_to 'Back', vip_categories_path

app/views/vip_categories/referencelist.html.haml
    
%div.panel.panel-info
  %div.panel-heading="List of References"
  %div.panel-body
    %table.table.table-striped
      -if !@referencelist.nil?
        %tr{:style=>'background-color: #F8F8F8; border:1px solid black;'}
          %td
            %b= "S.No."
          %td
            %b= "Ref No."
          %td
            %b= "Letter No."
          %td
            %b= "Letter Date"
          %td
            %b= "Subject"
          %td
            %b= "Dealing Section"
          %td
            %b= "VIP Cat."
          %td
            %b= "VIP Name"

          %td
            %b= "Status"
          %td
            %b= "Quick Action"
    
      - @referencelist.try :each_with_index do |reference,index|
        -if index%2==1
          %tr.even
            -if params[:page].to_i == 0
              %td= index+1
            -else
              %td= (params[:page].to_i-1)*10+index+1
            %td= reference.id
            %td=reference.letter_no
            %td=l reference.letter_date,format: :default
            %td=reference.subject  
            %td=reference.dealing_section.name
            %td=reference.vip_category.s_name
            %td
              =reference.sender.name
              %br
              =reference.sender.designation
            %td=reference.vip_ref_status.try(:status_name)
            %td=link_to 'View', reference
        -else
          %tr.odd
            -if params[:page].to_i == 0
              %td= index+1
            -else
              %td= (params[:page].to_i-1)*10+index+1
            %td= reference.id
            %td=reference.letter_no
            %td=l reference.letter_date,format: :default
            %td=reference.subject  
            %td=reference.dealing_section.name
            %td=reference.vip_category.s_name
            %td
              =reference.sender.name
              %br
              =reference.sender.designation
            %td=reference.vip_ref_status.try(:status_name)
            %td=link_to 'View', reference
    
      %tr
        %td{:colspan=>'12'}= will_paginate @referencelist, renderer: BootstrapPagination::Rails
        /%td= link_to 'Edit', edit_vip_reference_path(reference)
        /%td= link_to 'Destroy', reference, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/vip_categories/show.html.haml
%p#notice= notice
%div.panel.panel-info
  %div.panel-heading
    ="Show VIP Category"
  %div.panel-body
    %table.table
      %tr
        %td= "Name"
        %td=@vip_category.name
      %tr
        %td= "Short Name"
        %td= @vip_category.s_name
      %tr
        %td= "Is Default?"
        %td= @vip_category.default
      %tr
        %td= "Created At"
        %td= @vip_category.created_at.to_formatted_s(:long)
      %tr
        %td= "Updated At"
        %td= @vip_category.updated_at.to_formatted_s(:long)
        
= link_to 'Edit', edit_vip_category_path(@vip_category)
\|
= link_to 'Back', vip_categories_path