config/routes.rb
Rails.application.routes.draw do
 
  get 'categories/index'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/create'
  get 'category/index'
  get 'category/edit'
  get 'category/destroy'
  get 'category/new'
  get 'category/create'
  get 'categories/listofSubCategories'
  
  resources :designations
  
  get 'vip_ref_transfers/index'
  get 'vip_ref_transfers/new'
  get 'vip_ref_transfers/delete'
  get 'vip_ref_summaries/new'
  get 'vip_ref_summaries/index'
  get 'vip_ref_summaries/create'
  get 'vip_ref_summaries/destroy'
  get 'vip_ref_summaries/edit'
  get 'vip_ref_summaries/update'

  get 'vip_ref_app/inbox_section'
  get 'vip_ref_app/inbox'
  get 'vip_ref_app/draft'
  get 'vip_ref_app/sent'
  get 'vip_ref_app/home'
  get 'vip_ref_app/homescreen'
  get 'vip_ref_app/pending_report'
  get 'vip_ref_app/pending_report_1'
  get 'vip_ref_app/disposalreport'

  get 'vip_ref_app/monthwisereport'
  get 'vip_ref_app/statewisereport'
  
  
  
  get 'vip_ref_app/category_wise_pendency'
  get 'vip_ref_app/report'

  
  get 'vip_ref_app/closed'
  get 'vip_ref_app/chart'

  get 'vip_reference_movements/index'

  get 'vip_references/report'
  get 'vip_references/index'

  get 'vip_references/update'

  get 'vip_references/delete'

  get 'vip_references/new'

  get 'complaint_status/index'

  get 'complaint_status/update'

  get 'complaint_status/delete'

  get 'complaint_status/new'

  get 'complaint_status/create'
  
  root 'vip_ref_app#homescreen'
  resources :categories
  resources :vip_categories do
    member do
      get :referencelist
    end
  end
  resources :vip_ref_statuses
  resources :sections do
      member do
        
        get :pending_lessthan_1mth
        get :pending_lessthan_3mth
        get :pending_morethan_3mth
        get :updated_today
        
      end
  end
  
  resources :statuses
  resources :designations
  resources :countries do
    get 'update_states'
    resources :states
  end
  match '/complaints/search_form' => 'complaints#search_form', :via=> :get, :as => :search_form

  resources :complaints do
    resources :complaint_movements
    collection do
      get 'home'
      get 'move'
     end
  end
  
  resources :complaint_types
  resources :handlers
  resources :offices do
      resources :contacts do
        resources :feedbacks do
          resources :feedback_replies
        end
        
      end 
  end
    resources :vip_references do
    resources :vip_ref_summaries
    member do
      get :send
      post :move_to_inbox
    end

    resources :vip_ref_transfers do
    end
    
    resources :vip_ref_movements do
      get 'read'
      collection do
        get 'send'
      end
    end
  end
  
  resources :homes

  devise_for :users, :controllers => {:registrations => "registrations",:sessions=>"sessions"},path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  validates :feedback_text,length: { maximum: 100,
    
    too_long: "must have at most %{count} characters"
      },presence:true
  
  belongs_to :contact
  validates :contact,presence:true 

  has_many :feedback_replies
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_office, only: [:create,:new,:show,:index,:edit, :update, :destroy]
  before_action :set_feedback, only: [:show,:edit, :update, :destroy]
  before_action :set_contact, only: [:create,:new,:index,:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  def new
    @feedback= Feedback.new
  end
  def index
    if current_user.is_admin?
      @feedbacks = Feedback.all.paginate(page: params[:page], per_page: 10)  
    else
    @feedbacks = @contact.feedbacks.paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @feedback= Feedback.new(feedback_params)
    @feedback.contact= current_user.contact
    @feedback.submitted_on= DateTime.now
    respond_to do |format|
      if @feedback.save
        format.html { redirect_to [@office,@contact,@feedback], notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @feedback.update(contact_params)
        format.html { redirect_to [@contact,@feedback], notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @feedback.destroy
        
    respond_to do |format|
      format.html { redirect_to [@office,@contact,@feedback], notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    def set_contact
      @contact = Contact.find(params[:contact_id])
    end
    def set_office
      @office = Office.find(params[:office_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:feedback_text)
    end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.haml
= form_for [@office,@contact,@feedback] do |f|
  - if @feedback.errors.any?
    #error_explanation
      %h2= "#{pluralize(@country.errors.count, "error")} prohibited this country from being saved:"
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg

  %div.row.top-buffer
    %div.col-md-4=f.label :feedback_text
    %div.col-md-8=f.text_area :feedback_text, :class=>'form-control',:rows=>'8',:cols=>'12',:placeholder =>"Type Here..."
  %div.row.top-buffer
    %div.col-md-12
      = f.submit :class=>'btn btn-default', :value=>'Submit'

app/views/feedbacks/edit.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="Edit  Feedback"
  %div.panel-body
    %div.col-md-8
      = render 'form'
    %div.col-md-4

= link_to 'Back', office_contact_feedbacks_path(@office,@contact)

app/views/feedbacks/index.html.haml
%div.panel.panel-info
  %div.panel-heading
    ="Listing Feebacks"
  %div.panel-body
    %table.table
      %thead
        %tr
          %th #
          %th{:colspan=>'3'} Feedback Text
          %th Submitted By
          %th Submitted On
          %th Reply
          %th Quick Action
      %tbody      
        %tr
          = will_paginate @feedbacks, renderer: BootstrapPagination::Rails
      - @feedbacks.each_with_index do |feedback,index|
        %tr
          %td= index+1
          %td{:colspan=>'3'}= feedback.feedback_text
          %td= "#{feedback.contact.name}-#{feedback.contact.designation.name}"
          %td= l feedback.submitted_on
          
          %td
            - if feedback.feedback_replies.size>0
              =feedback.feedback_replies.last.reply_text
              %br
                %b
                  ="Replied On #{l feedback.feedback_replies[0].replied_on}"
          %td
            = icon_link_to [@office,@contact,feedback],{:icon => "glyphicon glyphicon-open-file"},{:title=>'Show'}
            = icon_link_to  edit_office_contact_feedback_path(@office,@contact,feedback),{:icon => "glyphicon glyphicon-edit"},{:title=>'Edit'}
            = icon_link_to [@office,@contact,feedback],{:icon => "glyphicon glyphicon-trash"},{:title=>'Delete',:method => :delete, :data => { :confirm => 'Are you sure?' }}

%br
= link_to 'New Feedback', new_office_contact_feedback_path(@office,@contact) 

app/views/feedbacks/new.html.haml
%div.panel.panel-info
  %div.panel-heading{:style=>"color: #23648d; font-weight: bolder;"}
    ="New  Feedback"
  %div.panel-body{:style=>"color: #23648d;"}
    %div.col-md-8
      = render 'form'
    %div.col-md-4
      %b="Instructions:"
      %br
      ="You may give your feedback/complaints/suggestions  about the application usage."  
      ="You will be replied here itself."  
= link_to 'Back', office_contact_feedbacks_path(@office,@contact)
|
= link_to 'List of Feedbacks', office_contact_feedbacks_path(@office,@contact)

app/views/feedbacks/show.html.haml
%p#notice= notice
%div.panel.panel-info
  %div.panel-heading
    ="Show Feedback"
  %div.panel-body
    %table.table
      %tr
        %td= "Feedback Text"
        %td=@feedback.feedback_text
      %tr
        %td= "Submitted On"
        %td= l @feedback.submitted_on
      %tr
        %td= "Submitted By"
        %td= @feedback.contact.name

      %tr
        %td= "Created At"
        %td= @feedback.created_at.to_formatted_s(:long)
      %tr
        %td= "Updated At"
        %td= @feedback.updated_at.to_formatted_s(:long)

      %tr
        %td= "Replies"
        %td
          - @feedback.feedback_replies.each_with_index do |fr,index|
            %br
            = "#{index+1}. #{fr.reply_text} (Replied On-#{l fr.replied_on})"
            %br

= link_to 'Edit', edit_office_contact_feedback_path(@office,@contact,@feedback)
\|
= link_to 'Back', office_contact_feedbacks_path(@office,@contact)

=link_to 'Reply', new_office_contact_feedback_feedback_reply_path(@office,@contact,@feedback)