config/routes.rb
Rails.application.routes.draw do
 
  get 'categories/index'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/create'
  get 'category/index'
  get 'category/edit'
  get 'category/destroy'
  get 'category/new'
  get 'category/create'
  get 'categories/listofSubCategories'
  
  resources :designations
  
  get 'vip_ref_transfers/index'
  get 'vip_ref_transfers/new'
  get 'vip_ref_transfers/delete'
  get 'vip_ref_summaries/new'
  get 'vip_ref_summaries/index'
  get 'vip_ref_summaries/create'
  get 'vip_ref_summaries/destroy'
  get 'vip_ref_summaries/edit'
  get 'vip_ref_summaries/update'

  get 'vip_ref_app/inbox_section'
  get 'vip_ref_app/inbox'
  get 'vip_ref_app/draft'
  get 'vip_ref_app/sent'
  get 'vip_ref_app/home'
  get 'vip_ref_app/homescreen'
  get 'vip_ref_app/pending_report'
  get 'vip_ref_app/pending_report_1'
  get 'vip_ref_app/disposalreport'

  get 'vip_ref_app/monthwisereport'
  get 'vip_ref_app/statewisereport'
  
  
  
  get 'vip_ref_app/category_wise_pendency'
  get 'vip_ref_app/report'

  
  get 'vip_ref_app/closed'
  get 'vip_ref_app/chart'

  get 'vip_reference_movements/index'

  get 'vip_references/report'
  get 'vip_references/index'

  get 'vip_references/update'

  get 'vip_references/delete'

  get 'vip_references/new'

  get 'complaint_status/index'

  get 'complaint_status/update'

  get 'complaint_status/delete'

  get 'complaint_status/new'

  get 'complaint_status/create'
  
  root 'vip_ref_app#homescreen'
  resources :categories
  resources :vip_categories do
    member do
      get :referencelist
    end
  end
  resources :vip_ref_statuses
  resources :sections do
      member do
        
        get :pending_lessthan_1mth
        get :pending_lessthan_3mth
        get :pending_morethan_3mth
        get :updated_today
        
      end
  end
  
  resources :statuses
  resources :designations
  resources :countries do
    get 'update_states'
    resources :states
  end
  match '/complaints/search_form' => 'complaints#search_form', :via=> :get, :as => :search_form

  resources :complaints do
    resources :complaint_movements
    collection do
      get 'home'
      get 'move'
     end
  end
  
  resources :complaint_types
  resources :handlers
  resources :offices do
      resources :contacts do
        resources :feedbacks do
          resources :feedback_replies
        end
        
      end 
  end
    resources :vip_references do
    resources :vip_ref_summaries
    member do
      get :send
      post :move_to_inbox
    end

    resources :vip_ref_transfers do
    end
    
    resources :vip_ref_movements do
      get 'read'
      collection do
        get 'send'
      end
    end
  end
  
  resources :homes

  devise_for :users, :controllers => {:registrations => "registrations",:sessions=>"sessions"},path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}

end

app/models/vip_ref_summary.rb
class VipRefSummary < ActiveRecord::Base
  validates :summary_text,length: { in: 3..500,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
      },presence:true
      
  validates :vip_reference,presence:true
  belongs_to :vip_reference
  belongs_to :creator, class_name: 'User'
end

app/controllers/vip_ref_summaries_controller.rb
class VipRefSummariesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_vip_reference, only: [:create, :show, :edit, :update, :destroy,:new,:index]
  before_action :set_vip_ref_summary, only: [:show,:edit,:update,:destroy]  
  def new
    @vip_ref_summary = VipRefSummary.new
    @vip_ref_summary.vip_reference = @vip_reference
    
  end
  def show
    
  end
  def index
      @vip_ref_summaries = @vip_reference.vip_ref_summaries.paginate(page: params[:page], per_page: 10)
            
  end

  def create
    @vip_ref_summary = VipRefSummary.new(vip_ref_summaries_params)
    @vip_ref_summary.creator_id = current_user.id
    @vip_ref_summary.vip_reference = @vip_reference
    
    respond_to do |format|
      if @vip_ref_summary.save
        format.html { redirect_to @vip_reference, notice: 'Reference was successfully Updated.' }
        format.json { render :show, status: :sent, location: @vip_reference }
      else
        format.html { render :new }
        format.json { render json: @vip_ref_summary.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vip_ref_summary.destroy
    respond_to do |format|
      format.html { redirect_to [@vip_reference,@vip_ref_summary], notice: 'Vip Reference Summary was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def edit

  end

  def update
    respond_to do |format|
      if @vip_ref_summary.update(vip_ref_summaries_params)
        format.html { redirect_to [@vip_reference,@vip_ref_summary], notice: 'Vip Reference Summary was successfully Updated.' }
        format.json { render :show, status: :sent, location: @vip_ref_summary }
      else
        format.html { render :edit }
        format.json { render json: @vip_ref_summary.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vip_ref_summary
    @vip_ref_summary= VipRefSummary.find(params[:id])
  end

  def set_vip_reference
    @vip_reference = VipReference.find(params[:vip_reference_id])
  end

  def vip_ref_summaries_params
      params.require(:vip_ref_summary).permit(:summary_text)
  end

end

app/helpers/vip_ref_summaries_helper.rb
module VipRefSummariesHelper
end

app/views/vip_ref_summaries/create.html.haml
%h1 VipRefSummaries#create
%p Find me in app/views/vip_ref_summaries/create.html.haml

app/views/vip_ref_summaries/destroy.html.haml
%h1 VipRefSummaries#destroy
%p Find me in app/views/vip_ref_summaries/destroy.html.haml

app/views/vip_ref_summaries/edit.html.haml
%div.panel.panel-info
  %div.panel-heading="Receipt Details"
  %div.panel-body
    %div.row
      %div.col-md-12
        %label.col-md-2= "Letter No"
        %div.col-md-4=@vip_reference.letter_no
        %label.col-md-2="Letter Date"
        %div.col-md-4=@vip_reference.letter_date.to_formatted_s(:long)         # => "18 Jan 06:10"
    %div.row
      %div.col-md-12
        %label.col-md-2= "Subject"
        %div.col-md-10=@vip_reference.subject
    %div.row
      %div.col-md-12
        %label.col-md-2= "Vip Name"
        %div.col-md-10=@vip_reference.sender.name

= form_for([@vip_reference,@vip_ref_summary]) do |f|
  %div.panel.panel-info
    %div.panel-heading="Status Summary Details"
    %div.panel-body
      %div.row.top-buffer
        %div.col-md-12
          %label.col-md-2= "Status Summary Update:"
          %div.col-md-10=f.text_area :summary_text,:cols=>'90',:rows=>'5',:class=>'form-control'

  %div.panel.panel-info
    %div.panel-body
      %div.row.top-buffer
        %div.col-md-10
        %div.col-md-2
          = f.submit 'Update', :class=> 'btn btn-primary'

=link_to 'Back', @vip_reference

app/views/vip_ref_summaries/index.html.haml
%script
  // this may cause nesting error this code is to be moved js file 
  function printPage() {
  $('#printable tr').find('th:last, td:last').hide();
  $('#printable').print();
  window.location.reload();
  }


%div.panel.panel-info
  %div.panel-heading
    ="VIP Reference's Summary History"
  %div.panel-body
    %div.row
      %div.col-md-12.col-md-offset-11
        =link_to 'Print', '#',:class=>'btn btn-default' ,:onclick=>"printPage()"
    %table.table#printable
      %thead
        %tr
          %th= "#"
          %th= "Summary Text"
          %th= "Created By"
          %th= "Created At"
          %th= "Updated At"
          %th= "Quick Action"    
      %tbody
        %tr
          = will_paginate @vip_ref_summaries, renderer: BootstrapPagination::Rails

      - @vip_ref_summaries.each_with_index do |vip_ref_summary,index|
        %tr
          -if params[:page].to_i == 0
            %td= index+1
          -else
            %td= (params[:page].to_i-1)*10+index+1

          %td= vip_ref_summary.summary_text
          %td= vip_ref_summary.creator.email
          %td= l vip_ref_summary.created_at
          %td= l vip_ref_summary.updated_at
          %td
            /
              = link_to 'Show', vip_reference_vip_ref_summary_path(@vip_reference,vip_ref_summary)
              = link_to 'Edit', edit_vip_reference_vip_ref_summary_path(@vip_reference,vip_ref_summary)
              = link_to 'Destroy', vip_reference_vip_ref_summary_path(@vip_reference,vip_ref_summary), :method => :delete, :data => { :confirm => 'Are you sure?' }

            = icon_link_to vip_reference_vip_ref_summary_path(@vip_reference,vip_ref_summary),{:icon => "glyphicon glyphicon-open-file"},{title:'Show'}
            = icon_link_to  edit_vip_reference_vip_ref_summary_path(@vip_reference,vip_ref_summary),{:icon => "glyphicon glyphicon-edit"},{title:'Edit'}
            = icon_link_to vip_reference_vip_ref_summary_path(@vip_reference,vip_ref_summary),{:icon => "glyphicon glyphicon-trash"},{:title=>'Delete',:method => :delete, :data => { :confirm => 'Are you sure?' }}


%br

= link_to 'New VIP Reference summary', new_vip_reference_vip_ref_summary_path

app/views/vip_ref_summaries/new.html.haml
%div.panel.panel-info
  %div.panel-heading="Receipt Details"
  %div.panel-body
    %div.row
      %div.col-md-12
        %label.col-md-2= "Letter No"
        %div.col-md-4=@vip_reference.letter_no
        %label.col-md-2="Letter Date"
        %div.col-md-4=@vip_reference.letter_date.to_formatted_s(:long)         # => "18 Jan 06:10"
    %div.row
      %div.col-md-12
        %label.col-md-2= "Subject"
        %div.col-md-10=@vip_reference.subject
    %div.row
      %div.col-md-12
        %label.col-md-2= "Vip Name"
        %div.col-md-10=@vip_reference.sender.name


= form_for([:vip_reference,@vip_ref_summary]) do |f|
  %div.panel.panel-info
    %div.panel-heading="Status Summary Details"
    %div.panel-body
      %div.row.top-buffer
        %div.col-md-12
          %label.col-md-2= "Status Summary Update:"
          %div.col-md-10=f.text_area :summary_text,:cols=>'90',:rows=>'5',:class=>'form-control'

  %div.panel.panel-info
    %div.panel-body
      %div.row.top-buffer
        %div.col-md-10
        %div.col-md-2
          = f.submit 'Update', :class=> 'btn btn-primary'

=link_to 'Back', @vip_reference

app/views/vip_ref_summaries/show.html.haml
%p#notice= notice
%div.panel.panel-info
  %div.panel-heading
    ="Show VIP Reference Summary"
  %div.panel-body
    %table.table
      %tr
        %td= "Summary Text"
        %td=@vip_ref_summary.summary_text
      %tr
        %td= "Created By"
        %td= @vip_ref_summary.creator.email
      %tr
        %td= "Created At"
        %td= l @vip_ref_summary.created_at
      %tr
        %td= "Updated At"
        %td= l @vip_ref_summary.updated_at


= link_to 'Edit', edit_vip_reference_vip_ref_summary_path(@vip_reference,@vip_ref_summary)
\|
= link_to 'Back', vip_reference_vip_ref_summaries_path

app/views/vip_ref_summaries/update.html.haml
%h1 VipRefSummaries#update
%p Find me in app/views/vip_ref_summaries/update.html.haml